"""Initial migration

Revision ID: 5cdae611a8d6
Revises: c0bce41246c2
Create Date: 2024-08-29 09:34:47.188585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cdae611a8d6'
down_revision = 'c0bce41246c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('namespace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('uri', sa.String(length=200), nullable=False),
    sa.Column('ontology_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ontology_id'], ['ontology.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'ontology_id', name='uq_namespace_name_ontology_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('namespace')
    # ### end Alembic commands ###
