"""Initial migration

Revision ID: 79934bddb64c
Revises: 5cdae611a8d6
Create Date: 2024-08-29 12:18:11.644408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79934bddb64c'
down_revision = '5cdae611a8d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('namespace', schema=None) as batch_op:
        batch_op.alter_column('uri',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('namespace', schema=None) as batch_op:
        batch_op.alter_column('uri',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
