"""Initial migration

Revision ID: c0bce41246c2
Revises: 
Create Date: 2024-08-29 09:28:54.923133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0bce41246c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ontology',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ontology_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ontology_id'], ['ontology.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['class.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'ontology_id', name='uq_class_name_ontology_id')
    )
    op.create_table('disjoint_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('disjoint_class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['disjoint_class_id'], ['class.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'disjoint_class_id', name='uq_disjoint_class')
    )
    op.create_table('equivalent_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('equivalent_class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['equivalent_class_id'], ['class.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'equivalent_class_id', name='uq_equivalent_class')
    )
    op.create_table('ontology_property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ontology_id', sa.Integer(), nullable=False),
    sa.Column('domain_class_id', sa.Integer(), nullable=False),
    sa.Column('range_class_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['domain_class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['ontology_id'], ['ontology.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['ontology_property.id'], ),
    sa.ForeignKeyConstraint(['range_class_id'], ['class.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'ontology_id', name='uq_property_name_ontology_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ontology_property')
    op.drop_table('equivalent_class')
    op.drop_table('disjoint_class')
    op.drop_table('class')
    op.drop_table('ontology')
    op.drop_table('user')
    # ### end Alembic commands ###
